#!/bin/sh

llvm-g++ -x c++ -o sample.ll -S -emit-llvm $* - <<EOF
#include <stdio.h>

class A {
public:
	A() {}
	~A() {}
};

void sub(int n)
{
	A a1, a2, a3;	
	if (n < 3) throw 3;
}

void hoge()
{
	try {
		
	}
	catch (int n) {
	}
}
EOF
